[package]
name = "circle-checker2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = {version = "0.13.1", features = ["yaml"]}
webbrowser = "0.7.1"
log = "0.4"
env_logger = "0.8"